server:
  port: 8082
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos.service.lruri.love
    alibaba:
      seata:
        tx-service-group: my_test_tx_group

  rabbitmq:
    host: public.service.lruri.love
    port: 5672
    username: admin
    password: admin
    # 设置虚拟主机
    virtual-host: delay-order
    connection-timeout: 15000
    # 用来配置消息发送到交换器之后是否触发回调方法
    publisher-confirm-type: correlated
    # 触发路由失败消息的回调
    publisher-returns: true
    template:
      # 必须设置成true 消息路由失败通知监听者，而不是将消息丢弃
      mandatory: true
    listener:
      simple:
        # 每次从RabbitMQ获取的消息数量(限流)
        prefetch: 1
        default-requeue-rejected: false
        # 每个队列启动的消费者数量
        concurrency: 1
        # 每个队列最大的消费者数量
        max-concurrency: 1
        # 手动确认
        acknowledge-mode: manual

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1ke3p9w5o4rq8dv0o.mysql.rds.aliyuncs.com:3306/orderdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: Peng2022
    hikari:
      pool-name: dataHikariCP
      minimum-idle: 5
      # 默认十分钟
      idle-timeout: 180000
      maximum-pool-size: 10
      max-lifetime: 180000
      auto-commit: true
      connection-timeout: 30000
      connection-test-query: SELECT 1

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.goal.order.entity
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1        # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0    # 逻辑未删除值(默认为 0)


seata:
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 106.55.10.118:8091
    enable-degrade: false
    disable-global-transaction: false

